### ISSUE TITLE
Apt error

### ISSUE THREAD

**Issue by vdel78** [Cairo-Dock/cairo-dock-plug-ins#20]
Hi every one,

Stable branch is no longer usable because of library dependencies.

So i install cairo-dock-plugins with the weekly version as recommended in the last reporting issue solution.

It works and install it well on ubuntu and pop os but apt gives some errors while updating repository:

```
for ubuntu(maybe debian i don't remember ;-(
~$ sudo apt update

Atteint :1 http://fr.archive.ubuntu.com/ubuntu noble InRelease
Atteint :2 http://security.ubuntu.com/ubuntu noble-security InRelease                                                   
Atteint :3 http://fr.archive.ubuntu.com/ubuntu noble-updates InRelease                                                  
Réception de :4 http://ppa.launchpad.net/cairo-dock-team/weekly/ubuntu noble InRelease [18,1 kB]
Atteint :5 http://fr.archive.ubuntu.com/ubuntu noble-backports InRelease
Réception de :6 http://ppa.launchpad.net/cairo-dock-team/weekly/ubuntu noble/main amd64 Packages [9 548 B]
Réception de :7 http://ppa.launchpad.net/cairo-dock-team/weekly/ubuntu noble/main Translation-en [5 000 B]
32,6 ko réceptionnés en 1s (57,6 ko/s)        
Lecture des listes de paquets... Fait

W: http://ppa.launchpad.net/cairo-dock-team/weekly/ubuntu/dists/noble/InRelease: La clé est stockée dans l'ancien trousseau de clés trust.gpg (/etc/apt/trusted.gpg), voir la section DÉPRÉCATION dans apt-key(8) pour plus de détails.
W: http://ppa.launchpad.net/cairo-dock-team/weekly/ubuntu/dists/noble/InRelease: La signature par clé 4E6B5E978E5D9070EBC365BA7274A4DAE80D6BF5 utilise un algorithme faible (rsa1024)
~$ sudo apt-get install cairo-dock cairo-dock-plug-ins
```

For Pop OS, only one error:
`W: http://ppa.launchpad.net/cairo-dock-team/weekly/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

**Comment by dkondor** [comment]
Hi,
thanks for reporting! Regarding the keys, this seems to be handled by Launchpad, see e.g. here:
https://answers.launchpad.net/launchpad/+question/809194

The solution seems to be to remove and add back to PPA:
```
sudo add-apt-repository -r ppa:cairo-dock-team/weekly
sudo add-apt-repository ppa:cairo-dock-team/weekly
```

Regarding the stable packages, I guess it would be time to try to update the stable repo as well -- I'll try to look into this in the coming days.

**Comment by dkondor** [comment]
Hi,
I've updated the stable repo: https://launchpad.net/~cairo-dock-team/+archive/ubuntu/ppa but let me know if you still have issues (with either version).

**Comment by vdel78** [comment]
Hi,
Tested on Ubuntu 24.04, it works well!
